# Autostart Apps

# Start XDG desktop autostart applications using dex in the i3 environment
exec --no-startup-id dex-autostart --autostart --environment i3

# Start xss-lock and run a custom lock script before suspend/sleep
exec --no-startup-id xss-lock --transfer-sleep-lock -- ~/.config/i3/scripts/display/lock.sh

# Start the NetworkManager system tray applet
exec --no-startup-id nm-applet

# Disable screen blanking timeout
exec_always --no-startup-id xset s off

# Disable DPMS (Energy Star) power management features
exec_always --no-startup-id xset -dpms

# Prevent the screen from blanking
exec_always --no-startup-id xset s noblank

# Start dunst notification daemon
exec --no-startup-id dunst

# Launch custom workspace listener script for the status bar
exec_always --no-startup-id ~/.config/i3/scripts/bar/bar_workspace_listener.sh

# Run battery monitoring script to send low battery notifications
#exec_always --no-startup-id ~/.config/i3/scripts/battery/battery_notify.sh

# Swap Ctrl and Caps Lock keys
exec --no-startup-id setxkbmap -option ctrl:swapcaps
