# Autostart Apps

exec --no-startup-id dex-autostart --autostart --environment i3
# I used i3lock-color for this one (you probably need to install it)
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork --color=141416 --clock --indicator --ring-width=0 --inside-color=00000000 --time-color=ffffffff --date-color=ffffffff
#exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id nm-applet
exec_always --no-startup-id xset s off
exec_always --no-startup-id xset -dpms

# Run screen layout script on start and on reload
exec_always /home/youness_sbai/.config/i3/scripts/display/auto_monitor_setup.sh

exec_always --no-startup-id ~/.config/i3/scripts/bar/bar_workspace_listener.sh

# Swap ctrl with caps key
exec --no-startup-id setxkbmap -option ctrl:swapcaps
