# Workspace names
# Define custom names for each workspace
# Workspace 1 for web browsing
set $ws1 "1: Web"
# Workspace 2 for terminal applications
set $ws2 "2: Terminal"
# Workspace 3 for virtual machines
set $ws3 "3: VMs"
# Workspace 4 for notes taking
set $ws4 "4: Notes"
# Workspace 5 for file management
set $ws5 "5: Thunar"
# Generic workspace 6
set $ws6 "6"
# Workspace 7 for gaming
set $ws7 "7: Gaming"
# Workspace 8 for streaming and recording
set $ws8 "8: Streaming"
# Workspace 9 for Communication
set $ws9 "9: Communication"
# Workspace 10 for Spotify/music
set $ws10 "10: Spotify"


# Switch to workspace
# Keybindings for changing active workspaces
# These bindings use an AZERTY keyboard layout
# Switch to workspace 1
bindsym $mod+ampersand workspace number $ws1
# Switch to workspace 2
bindsym $mod+eacute workspace number $ws2
# Switch to workspace 3
bindsym $mod+quotedbl workspace number $ws3
# Switch to workspace 4
bindsym $mod+apostrophe workspace number $ws4
# Switch to workspace 5
bindsym $mod+parenleft workspace number $ws5
# Switch to workspace 6
bindsym $mod+minus workspace number $ws6
# Switch to workspace 7
bindsym $mod+egrave workspace number $ws7
# Switch to workspace 8
bindsym $mod+underscore workspace number $ws8
# Switch to workspace 9
bindsym $mod+ccedilla workspace number $ws9
# Switch to workspace 10
bindsym $mod+agrave workspace number $ws10


# Move focused container to workspace
# Move the currently focused window to another workspace
# Move focused window to workspace 1
bindsym $mod+Shift+ampersand move container to workspace number $ws1
# Move focused window to workspace 2
bindsym $mod+Shift+eacute move container to workspace number $ws2
# Move focused window to workspace 3
bindsym $mod+Shift+quotedbl move container to workspace number $ws3
# Move focused window to workspace 4
bindsym $mod+Shift+apostroph4e move container to workspace number $ws4
# Move focused window to workspace 5
bindsym $mod+Shift+5 move container to workspace number $ws5
# Move focused window to workspace 6
bindsym $mod+Shift+minus move container to workspace number $ws6
# Move focused window to workspace 7
bindsym $mod+Shift+egrave move container to workspace number $ws7
# Move focused window to workspace 8
bindsym $mod+Shift+underscore move container to workspace number $ws8
# Move focused window to workspace 9
bindsym $mod+Shift+ccedilla move container to workspace number $ws9
# Move focused window to workspace 10
bindsym $mod+Shift+agrave move container to workspace number $ws10


# Assign applications to specific workspaces
# Automatically sends matching applications to predefined workspaces
# Open Firefox on workspace 1 (Web)
assign [class="org.mozilla.firefox"] $ws1
# Open Kitty terminal on workspace 2 (Terminal)
assign [class="kitty"] $ws2
# Open VMware on workspace 3 (VMs)
assign [class="Vmware"] $ws3
# Open Obsidian on workspace 4 (Notes Taking)
assign [class="obsidian"] $ws4
# Open Thunar on workspace 5 (File Manager)
assign [class="Thunar"] $ws5
# Open OBS Studio on workspace 8 (Streaming)
assign [class="^obs$"] $ws8
# Open Discord on workspace 9
assign [class="discord"] $ws9
# Open ZapZap on workspace 9
assign [class="ZapZap"] $ws9
# Open Spotify on workspace 10
assign [class="Spotify"] $ws10
